
package currencyconverter;
public class Converter extends javax.swing.JFrame {

    double Taka=1.00;
    double Rupee=1.21;
    double Dollar= 83.98;
    double Real=22.03;
    double Euro=95.25;
    double Ringgit=20.54;
    
            
            
    public Converter() {
        initComponents();
        setTitle(" Never Fail");
        setSize(800,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb1 = new javax.swing.JComboBox<>();
        cbtn1 = new javax.swing.JButton();
        rbtn2 = new javax.swing.JButton();
        ebtn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb2 = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        display = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose one...", "Rupee", "Dollar", "Euro", "Real", "Taka", "Ringgit" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 303, 100, 50));

        cbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtn1.setText("Convert");
        cbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 398, 101, 52));

        rbtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn2.setText("Reset");
        rbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 400, 101, 49));

        ebtn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ebtn3.setText("Exit");
        ebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(ebtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 398, 101, 52));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("                  Currency Converter ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 822, 78));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Input");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 246, -1, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("From of");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 246, 101, 50));

        cmb2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose one...", "Rupee", "Dollar", "Euro", "Real", "Taka", "Ringgit", " " }));
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 303, 100, 50));

        input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 303, 101, 50));

        display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 136, 419, 92));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("To of");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 87, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn2ActionPerformed
      display.setText("");
      input.setText("");
      
    }//GEN-LAST:event_rbtn2ActionPerformed

    private void cbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtn1ActionPerformed
        if(!input.getText().equals(true)){
            display.setText("Please give input");
        }
        if(cmb2.getSelectedItem().equals("Euro")){
            if(cmb1.getSelectedItem().equals("Rupee")){
                double d=Double.parseDouble(input.getText()); 
                String convert1;
                convert1=String.format("Euro %.2f",(d*Rupee)/Euro);
                display.setText(convert1);
            }
            else if(cmb1.getSelectedItem().equals("Real")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Euro %.2f",(d*Real)/Euro);
                display.setText(convert1);
           }
             else if(cmb1.getSelectedItem().equals("Taka")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Euro %.2f",d/Euro);
                display.setText(convert1);
             }
            else if(cmb1.getSelectedItem().equals("Dollar")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Euro %.2f",(d*Dollar)/Euro);
                display.setText(convert1);
            }
            else if(cmb1.getSelectedItem().equals("Ringgit")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Euro %.2f",(d*Ringgit)/Euro);
                display.setText(convert1);
            }
            else if(cmb1.getSelectedItem().equals("Euro")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Euro %.2f",d);
                display.setText(convert1);
            }
        }
        
        
        
        
        else if(cmb2.getSelectedItem().equals("Real")){
                if(cmb1.getSelectedItem().equals("Rupee")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Real %.2f",(d*Rupee)/Real);
                    display.setText(Convert1);
                    
                    }
               else if(cmb1.getSelectedItem().equals("Taka")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Real %.2f",d/Real);
                    display.setText(Convert1);
                }
               else if(cmb1.getSelectedItem().equals("Dollar")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Real %.2f",(d*Dollar)/Real);
                    display.setText(Convert1);
                    }
               else if(cmb1.getSelectedItem().equals("Euro")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Real %.2f",(d*Euro)/Real);
                    display.setText(Convert1);
                } 
               else if(cmb1.getSelectedItem().equals("Ringgit")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Real %.2f",(d*Ringgit)/Real);
                    display.setText(Convert1);
                }
                else if(cmb1.getSelectedItem().equals("Real")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("%.2f Real",d);
                display.setText(convert1);
            }
            
        }
        
        
        
        
        
        else if(cmb2.getSelectedItem().equals("Taka")){
                if(cmb1.getSelectedItem().equals("Rupee")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Taka %.2f /-",d*Rupee);
                    display.setText(Convert1);
                    
                    }
               else if(cmb1.getSelectedItem().equals("Real")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Taka %.2f /-",d*Real);
                    display.setText(Convert1);
                }
             else if(cmb1.getSelectedItem().equals("Dollar")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Taka %.2f /-",d*Dollar);
                    display.setText(Convert1);
                    }
               else if(cmb1.getSelectedItem().equals("Euro")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Taka %.2f /-",d*Euro);
                    display.setText(Convert1);
                } 
               else if(cmb1.getSelectedItem().equals("Ringgit")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Taka %.2f /-",d*Ringgit);
                    display.setText(Convert1);
                }
                else if(cmb1.getSelectedItem().equals("Taka")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("Taka %.2f /-",d);
                display.setText(convert1);
            }
            
        }
        
        
        
        else if(cmb2.getSelectedItem().equals("Dollar")){
                if(cmb1.getSelectedItem().equals("Rupee")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f $",(d*Rupee)/Dollar);
                    display.setText(Convert1);
                    
                    }
               else if(cmb1.getSelectedItem().equals("Taka")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f $",d/Dollar);
                    display.setText(Convert1);
                }
              else if(cmb1.getSelectedItem().equals("Real")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f $",(d*Real)/Dollar);
                    display.setText(Convert1);
                    }
               else if(cmb1.getSelectedItem().equals("Euro")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f $",(d*Euro)/Dollar);
                    display.setText(Convert1);
                } 
               else if(cmb1.getSelectedItem().equals("Ringgit")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f $",(d*Ringgit)/Dollar);
                    display.setText(Convert1);
                }
                else if(cmb1.getSelectedItem().equals("Dollar")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("%.2f $",d);
                display.setText(convert1);
            }
                
        }
        
        
        
        else if(cmb2.getSelectedItem().equals("Rupee")){
                if(cmb1.getSelectedItem().equals("Real")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Rupee %.2f",d*Real*Rupee);
                    display.setText(Convert1);
                    
                    }
                else if(cmb1.getSelectedItem().equals("Taka")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Rupee %.2f",d*Taka*Rupee);
                    display.setText(Convert1);
                }
              else if(cmb1.getSelectedItem().equals("Dollar")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Rupee %.2f",d*Dollar*Rupee);
                    display.setText(Convert1);
                    }
               else if(cmb1.getSelectedItem().equals("Euro")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Rupee %.2f",d*Euro*Rupee);
                    display.setText(Convert1);
                } 
               else if(cmb1.getSelectedItem().equals("Ringgit")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("Rupee %.2f",d*Ringgit*Rupee);
                    display.setText(Convert1);
                }
                else if(cmb1.getSelectedItem().equals("Rupee")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("%.2f Rupee",d);
                display.setText(convert1);
            }
                
        }
                
                
                
                
                
                
            else if(cmb2.getSelectedItem().equals("Ringgit")){
                if(cmb1.getSelectedItem().equals("Rupee")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f Ringgit",(d*Rupee)/Ringgit);
                    display.setText(Convert1);
                    
                    }
               else if(cmb1.getSelectedItem().equals("Taka")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f Ringgit",d/Ringgit);
                    display.setText(Convert1);
                }
              else if(cmb1.getSelectedItem().equals("Real")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f Ringgit",(d*Real)/Ringgit);
                    display.setText(Convert1);
                    }
               else if(cmb1.getSelectedItem().equals("Euro")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f Ringgit",(d*Euro)/Ringgit);
                    display.setText(Convert1);
                } 
               else if(cmb1.getSelectedItem().equals("Dollar")){
                    double d =Double.parseDouble(input.getText());
                    String Convert1=String.format("%.2f Ringgit",(d*Dollar)/Ringgit);
                    display.setText(Convert1);
                }
                else if(cmb1.getSelectedItem().equals("Ringgit")){
                double d=Double.parseDouble(input.getText()); 
                String convert1=String.format("%.2f Ringgit",d);
                display.setText(convert1);
            }
        }
      
        
        
        else
        {
            display.setText("Plese Give input");
        }
 
        
    }//GEN-LAST:event_cbtn1ActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        cmb1.getSelectedItem();
        
    }//GEN-LAST:event_cmb1ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed
        cmb2.getSelectedItem();
    }//GEN-LAST:event_cmb2ActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        input.getText();
    }//GEN-LAST:event_inputActionPerformed

    private void ebtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtn3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ebtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn1;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JLabel display;
    private javax.swing.JButton ebtn3;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton rbtn2;
    // End of variables declaration//GEN-END:variables
}
